name: rewearth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.12  # âœ… Tambahan untuk notifikasi toast
  firebase_core: ^3.0.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  image_picker: ^1.0.7 # atau versi terbaru yang tersedia
  camera: ^0.10.5+9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/google_icon.png
    - lib/assets/images/Kategori1.png
    - lib/assets/images/kategori2.png
    - lib/assets/images/kategori3.png
    - lib/assets/images/kategori4.png
    - lib/assets/images/barter.png
    - lib/assets/images/donasi.png
    - lib/assets/images/tantangan.png
    - lib/assets/images/voucher.png
    - lib/assets/images/takeback.png
    - lib/assets/images/profile.png
    - lib/assets/images/Coin.png
    - lib/assets/images/notif.png
    - lib/assets/images/chat.png
    - lib/assets/images/baju1.png
    - lib/assets/images/baju2.png
    - lib/assets/images/baju3.png
    - lib/assets/images/baju4.png
    - lib/assets/images/Search.png
    - lib/assets/images/Filter.png
    - lib/assets/images/luv.png
    - lib/assets/images/bagikan.png
    - lib/assets/images/comment.png
    - lib/assets/images/favorit.png
    - lib/assets/images/video.png
    - lib/assets/images/edit.png
    - lib/assets/images/uniqlo.png
    - lib/assets/images/settings.png
    - lib/assets/images/produkmu.png
    - lib/assets/images/keamanan.png
    - lib/assets/images/ubah_password.png
    - lib/assets/images/lupa_password.png
    - lib/assets/images/riwayat.png
    - lib/assets/images/coinblack.png
    - lib/assets/images/SR.png
    - lib/assets/images/rumahzakat.png
    - lib/assets/images/yatim.png
    - lib/assets/images/drop_point.png
    - lib/assets/images/preview.png
    - lib/assets/images/background.png
    - lib/assets/images/hm.png
    - lib/assets/images/zara.png
    - lib/assets/images/voucher-uniqlo.png
    - lib/assets/images/icon_verifikasi.png
    - lib/assets/images/logoAPK.png
    - lib/assets/images/logoAPK2.png

dependency_overrides:
  firebase_auth_platform_interface: ^7.0.3
